const videoSeeds = [
  {
    title: "Amarillo",
    description: "Learn the sign for 'Amarillo' (Yellow) in sign language.",
    video_url: "https://www.youtube.com/embed/LUve7X89p4o",
    category: "Colores 1",
  },
  {
    title: "Azul",
    description: "Learn the sign for 'Azul' (Blue) in sign language.",
    video_url: "https://www.youtube.com/embed/96emnqpLivk?si=NzzteaDgWFsXe7ZX",
    category: "Colores 1",
  },
  {
    title: "Blanco",
    description: "Learn the sign for 'Blanco' (White) in sign language.",
    video_url: "https://www.youtube.com/embed/81RSmORa_VI",
    category: "Colores 1",
  },
  {
    title: "Gris",
    description: "Learn the sign for 'Gris' (Gray) in sign language.",
    video_url: "https://www.youtube.com/embed/FGvuOur1CUw",
    category: "Colores 1",
  },
  {
    title: "Naranja",
    description: "Learn the sign for 'Naranja' (Orange) in sign language.",
    video_url: "https://www.youtube.com/embed/AGLPZt9dTvE",
    category: "Colores 1",
  },
  {
    title: "Negro",
    description: "Learn the sign for 'Negro' (Black) in sign language.",
    video_url: "https://www.youtube.com/embed/WZ7-2xWRzXs",
    category: "Colores 1",
  },
  {
    title: "Rojo",
    description: "Learn the sign for 'Rojo' (Red) in sign language.",
    video_url: "https://www.youtube.com/embed/4zCfWmvta8s",
    category: "Colores 1",
  },
  {
    title: "Rosa",
    description: "Learn the sign for 'Rosa' (Pink) in sign language.",
    video_url: "https://www.youtube.com/embed/K16-MDlcuzY",
    category: "Colores 1",
  },
  {
    title: "Verde",
    description: "Learn the sign for 'Verde' (Green) in sign language.",
    video_url: "https://www.youtube.com/embed/7vVKAK3EQw8",
    category: "Colores 1",
  },
  {
    title: "Color",
    description: "Learn the sign for 'Color' in sign language.",
    video_url: "https://www.youtube.com/embed/89jWhUucKrk",
    category: "Colores 1",
  },
  {
    title: "Numero 1",
    description: "Learn the sign for '1' in sign language.",
    video_url: "https://www.youtube.com/embed/8QT7MlxaSPU",
    category: "Numeros 1",
  },
  {
    title: "Numero 2",
    description: "Learn the sign for '2' in sign language.",
    video_url: "https://www.youtube.com/embed/Qjh9gCLGDsQ",
    category: "Numeros 1",
  },
  {
    title: "Numero 3",
    description: "Learn the sign for '3' in sign language.",
    video_url: "https://www.youtube.com/embed/md19qfUEZcY",
    category: "Numeros 1",
  },
  {
    title: "Numero 4",
    description: "Learn the sign for '4' in sign language.",
    video_url: "https://www.youtube.com/embed/3YQKE8dGP5I",
    category: "Numeros 1",
  },
  {
    title: "Numero 5",
    description: "Learn the sign for '5' in sign language.",
    video_url: "https://www.youtube.com/embed/rcrZHFa7J1k",
    category: "Numeros 1",
  },
  {
    title: "Numero 6",
    description: "Learn the sign for '6' in sign language.",
    video_url: "https://www.youtube.com/embed/ClJQ5uOdyb4",
    category: "Numeros 1",
  },
  {
    title: "Numero 7",
    description: "Learn the sign for '7' in sign language.",
    video_url: "https://www.youtube.com/embed/d0kV77RjY34",
    category: "Numeros 1",
  },
  {
    title: "Numero 8",
    description: "Learn the sign for '8' in sign language.",
    video_url: "https://www.youtube.com/embed/rcrZHFa7J1k",
    category: "Numeros 1",
  },
  {
    title: "Numero 9",
    description: "Learn the sign for '9' in sign language.",
    video_url: "https://www.youtube.com/embed/Noz54rVfSHM",
    category: "Numeros 1",
  },
  {
    title: "Hola",
    description: "Learn the sign for 'Hola' in sign language.",
    video_url: "https://www.youtube.com/embed/VWnQGLJDY6M",
    category: "Saludos 1",
  },
  {
    title: "Adios",
    description: "Learn the sign for 'Adios' in sign language.",
    video_url: "https://www.youtube.com/embed/WOYf6RKwKrY",
    category: "Saludos 1",
  },
  {
    title: "¿Como estas?",
    description: "Learn the sign for '¿Como estas?' in sign language.",
    video_url: "https://www.youtube.com/embed/Noz54rVfSHM",
    category: "Saudos 1",
  },
  {
    title: "Bien",
    description: "Learn the sign for 'Bien' in sign language.",
    video_url: "https://www.youtube.com/embed/fBR6AQYJn7Q",
    category: "Saludos 1",
  },
  {
    title: "Mal",
    description: "Learn the sign for 'Mal' in sign language.",
    video_url: "https://www.youtube.com/embed/BuQlORSNqe4",
    category: "Saludos 1",
  },
  {
    title: "Buenos días",
    description: "Learn the sign for 'Buenos días' in sign language.",
    video_url: "https://www.youtube.com/embed/hlyzuBBNTlc",
    category: "Saludos 1",
  },
  {
    title: "Buenas tardes",
    description: "Learn the sign for 'Buenas tardes' in sign language.",
    video_url: "https://www.youtube.com/embed/DEAAQnhf1WQ",
    category: "Saudos 1",
  },
  {
    title: "Buenas noches",
    description: "Learn the sign for 'Buenas noches' in sign language.",
    video_url: "https://www.youtube.com/embed/x_2XWzfibMk",
    category: "Saludos 1",
  },
  {
    title: "Mas o menos",
    description: "Learn the sign for 'Mas o menos' in sign language.",
    video_url: "https://www.youtube.com/embed/wztH0N3EZy0",
    category: "Saludos 1",
  },
  {
    title: "Oso",
    description: "Learn the sign for 'Oso' in sign language.",
    video_url: "https://www.youtube.com/embed/GLQBgHN47u0",
    category: "Animales 1",
  },
  {
    title: "Lobo",
    description: "Learn the sign for 'Lobo' in sign language.",
    video_url: "https://www.youtube.com/embed/fBnv7OeL_V4",
    category: "Animales 1",
  },
  {
    title: "Vaca",
    description: "Learn the sign for 'Vaca' in sign language.",
    video_url: "https://www.youtube.com/embed/Bg1R9QHDTGs",
    category: "Animales 1",
  },
  {
    title: "Toro",
    description: "Learn the sign for 'Toro' in sign language.",
    video_url: "https://www.youtube.com/embed/UFT-2kVtFqg",
    category: "Animales 1",
  },
  {
    title: "Burro",
    description: "Learn the sign for 'Burro' in sign language.",
    video_url: "https://www.youtube.com/embed/SFjFJcUnHNI",
    category: "Animales 1",
  },
  {
    title: "Jifara",
    description: "Learn the sign for 'Jifara' in sign language.",
    video_url: "https://www.youtube.com/embed/65hzLbqQ20A",
    category: "Animales 1",
  },
  {
    title: "Ardilla",
    description: "Learn the sign for 'Ardilla' in sign language.",
    video_url: "https://www.youtube.com/embed/7-pfLGCsPII",
    category: "Animales 1",
  },
  {
    title: "Cocodrillo",
    description: "Learn the sign for 'Cocodrillo' in sign language.",
    video_url: "https://www.youtube.com/embed/hcKRLsNA-wo",
    category: "Animales 1",
  },
  {
    title: "Tigre",
    description: "Learn the sign for 'Tigre' in sign language.",
    video_url: "https://www.youtube.com/embed/ipSGYN-tTGk",
    category: "Animales 1",
  },
  {
    title: "Leon",
    description: "Learn the sign for 'Leon' in sign language.",
    video_url: "https://www.youtube.com/embed/dcCEXgXtYOo",
    category: "Animales 1",
  },
];

module.exports = videoSeeds;
